name: Greber Skilk Screen Test

on: [push]

jobs:
  greber-check:
    runs-on: ubuntu-latest
    env:
      TESSDATA_PREFIX: /usr/share/tessdata

    steps:
      - uses: actions/checkout@v3
      - name: Install Gerbv
        run: |
          sudo apt-get update
          sudo apt-get install -y gerbv
      - name: Convert Silk Screen to PNG
        run: |
          gerbv -x png -o /tmp/package.png PCBExport/GerberFiles/silkscreen_top.gbr -D 1000
      - name: Install Tesseract OCR
        run: |
          sudo apt-get install -y tesseract-ocr
          wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata
          mkdir -p /usr/share/tessdata
          sudo mv eng.traineddata /usr/share/tessdata
      - name: Extract Text from Silk Screen
        run: |
          tesseract /tmp/package.png /tmp/package --dpi 1000 --psm 11 --oem 0

      - name: Push image to release
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: /tmp/package.png
      - name: Output Text
        run: |
          cat /tmp/package.txt
      - name: Check for "Team" 
        run: |
          nl /tmp/package.txt | grep -i team
          if [ $? -ne 0 ]; then
            echo "Team not found"
            exit 1
          fi
      
        
        
      